name: Easy platinums
env:
  DEFAULT_PROFILE_NAMES: ikemenzi,Fluttezuhher,chris_play1,IBadDriverI
on:
  workflow_dispatch:
    inputs:
      profile-name:
        type: choice
        description: PSN Profile to use to determine easy platinums
        required: true
        default: 'ikemenzi'
        options:
          - ikemenzi
          - Fluttezuhher
          - chris_play1
          - IBadDriverI
  schedule:
    - cron:  '30 5,17 * * *'
jobs:
  update:
    name: Update list of easy platinums
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Fetch new easy platinums
        run: |
          PROFILES=${{ github.event.inputs.profile-name || env.DEFAULT_PROFILE_NAMES }}
          for $profile in ${PROFILES//,/ } ; do 
            echo "+ \"$profile\""
          done
          bin/easy-platinums fetch ${{ github.event.inputs.profile-name }}

      - name: Update README.md and pages
        run: bin/easy-platinums update

      - name: Commit and push changes
        run: |
          git config --global user.name 'robiningelbrecht'
          git config --global user.email 'robiningelbrecht@users.noreply.github.com'
          git add .
          git commit -m "Automated update of README.md" --allow-empty
          git push
