name: Easy platinums
env:
  DEFAULT_PROFILE_NAMES: ViensDanser,Fluttezuhher,chris_play1,IBadDriverI,roots52,The-Ricksterr,Hakoom,ikemenzi
on:
  workflow_dispatch:
    inputs:
      profile-name:
        type: choice
        description: PSN Profile to use to determine easy platinums
        required: true
        default: 'ViensDanser'
        options:
          - ViensDanser
          - Fluttezuhher
          - chris_play1
          - IBadDriverI
          - roots52
          - The-Ricksterr
          - Hakoom
          - ikemenzi
          - ViensDanser,Fluttezuhher,chris_play1,IBadDriverI,roots52,The-Ricksterr,Hakoom,ikemenzi
  schedule:
    - cron:  '30 */4 * * *'
jobs:
  update:
    name: Update list of easy platinums
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: intl

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run test suite
        run: vendor/bin/phpunit --fail-on-incomplete

      - name: Fetch new easy platinums
        run: |
          PROFILES=${{ github.event.inputs.profile-name || env.DEFAULT_PROFILE_NAMES }}
          export COMMIT_MESSAGE=$(bin/easy-platinums games:fetch $PROFILES)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Update README.md and pages
        run: bin/easy-platinums files:update

      - name: Commit and push changes
        run: |
          git config --global user.name 'robiningelbrecht'
          git config --global user.email 'robiningelbrecht@users.noreply.github.com'
          git add .
          git status
          [[ ! -z "$COMMIT_MESSAGE" ]] && REAL_COMMIT_MESSAGE=$COMMIT_MESSAGE || REAL_COMMIT_MESSAGE="Statistics update"
          git diff --staged --quiet || git commit -m"$REAL_COMMIT_MESSAGE"
          git push
