name: Easy platinums
on:
  workflow_dispatch:
jobs:
  update:
    name: Update list of easy platinums
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run test suite
        run: vendor/bin/phpunit --fail-on-incomplete

      - name: Fetch new easy platinums
        run: |
          PROFILES=caro3c-gabber9,Fluttezuhher,chris_play1,IBadDriverI,roots52,The-Ricksterr,Hakoom,ikemenzi
          export COMMIT_MESSAGE=$(bin/easy-platinums games:fetch $PROFILES)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Update README.md and pages
        run: bin/easy-platinums files:update

      - name: Commit and push changes
        run: |
          git config --global user.name 'robiningelbrecht'
          git config --global user.email 'robiningelbrecht@users.noreply.github.com'
          git add .
          git status
          [[ ! -z "$COMMIT_MESSAGE" ]] && REAL_COMMIT_MESSAGE=$COMMIT_MESSAGE || REAL_COMMIT_MESSAGE="Statistics update"
          git diff --staged --quiet || git commit -m"$REAL_COMMIT_MESSAGE"
          git push
